apm-server:
  host: "0.0.0.0:8200"

  kibana:
    enabled: true
    host: "http://kibana_container:5601"
    username: "kibana_system"
    password: "kibana123"

auth:
  secret_token: ""

output.elasticsearch:
  hosts: ["http://elasticsearch_container:9200"]
  enabled: true
  protocol: "http"
  username: "elastic"
  password: "admin1234"
  ssl.enabled: false

monitoring.enabled: true

monitoring.elasticsearch:
  protocol: "http"
  username: "elastic"
  password: "admin1234"
  hosts: ["http://elasticsearch_container:9200"]

# npm install elastic-apm-node --save
# docker compose up -d apmServer
